function createrectangle(figure1)
%CREATERECTANGLE(figure1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 23-Sep-2021 13:31:05

% Create rectangle
annotation(figure1,'rectangle',[0.244 0.648 0.514 0.328]);

